language: java
jdk:
- oraclejdk8
env:
  global:
  - secure: PFI6yZ/7gtGdkCwZ7EkMHsaj3JzPOEal46GmToJUNkU6/RUqd+DlU+Bv9WCGF7GB5groXtssey3ukUZRBskFX4RhLO/RMFmvFyyWzMBLCqqwxBJassZohKL6HH/oWsG0xlnWfInjqlvbFFgLwH8yeiJZpnAugpHlzmU9WLy2z8Y=
  - secure: WUjygOPgtYDPB/oQ4U9S7lTNdrFWQzwVI8ucDXZuG4QWdii4BFeUBBv8vXrdU4K/+zVCvRMVTl++y2Yp46+OcULFAQZFq9E5J4mKszd8HIm7s+K7NN/iAleuDclQArP19tHWQ9MezkA4qoia4qmNZIZoJkXp0/UvahmtHLXl4dQ=
